'use strict';

module.exports = {
  Bucket: require('./bucket'),
  PublicKey: require('./pubkey'),
  User: require('./user'),
  OldUser: require('./oldUser'),
  UserNonce: require('./usernonce'),
  Token: require('./token'),
  Contact: require('./contact'),
  BucketEntry: require('./bucketentry'),
  FarmerHeft: require('./farmer-heft'),
  Farmer: require('./farmer'),
  Frame: require('./frame'),
  Pointer: require('./pointer'),
  Shard: require('./shard'),
  Credit: require('./credit'),
  Debit: require('./debit'),
  Mirror: require('./mirror'),
  ExchangeReport: require('./exchange-report'),
  PaymentProcessor: require('./payment-processor'),
  FullAudit: require('./full-audit'),
  Marketing: require('./marketing'),
  Referral: require('./referral'),
  StorageEvent: require('./storage-event'),
  Partner: require('./partner'),
  PayTransactions: require('./pay-transaction'),
  PaymentInfo: require('./paymentinfo'),
  KeyPair: require('./key-pair'),
  WithdrawRecord: require('./withdrawRecord'),
  ChainRecord : require('./chainRecord'),
  Share: require('./share'),
  NickName: require('./nickName')
};
